services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.10
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 20
      ZOOKEEPER_SYNC_LIMIT: 5
    volumes:
      - /opt/zookeeper/data:/var/lib/zookeeper/data
      - /opt/zookeeper/log:/var/lib/zookeeper/log
    networks:
      - kafka-network

  kafka_1:
    image: confluentinc/cp-kafka:7.0.10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_1:9092,EXTERNAL://192.168.1.129:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /opt/kafka/kafka_1:/var/lib/kafka/data
    networks:
      - kafka-network
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    restart: always

  kafka_2:
    image: confluentinc/cp-kafka:7.0.10
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,EXTERNAL://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_2:9094,EXTERNAL://192.168.1.129:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /opt/kafka/kafka_2:/var/lib/kafka/data
    networks:
      - kafka-network
    ports:
      - "9094:9094"
      - "9095:9095"
    depends_on:
      - zookeeper
    restart: always

  kafka_3:
    image: confluentinc/cp-kafka:7.0.10
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9096,EXTERNAL://0.0.0.0:9097
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_3:9096,EXTERNAL://192.168.1.129:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /opt/kafka/kafka_3:/var/lib/kafka/data
    networks:
      - kafka-network
    ports:
      - "9096:9096"
      - "9097:9097"
    depends_on:
      - zookeeper
    restart: always

  schema-registry:
   image: confluentinc/cp-schema-registry:latest
   depends_on:
     - kafka_1
     - kafka_2
     - kafka_3
   ports:
     - "8081:8081"
   networks:
      - kafka-network
   environment:
     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka_1:9092,PLAINTEXT://kafka_2:9094,PLAINTEXT://kafka_3:9096
     SCHEMA_REGISTRY_HOST_NAME: schema-registry
     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
   image: provectuslabs/kafka-ui
   networks:
     - kafka-network
   depends_on:
     - kafka_1
     - kafka_2
     - kafka_3
   ports:
     - "8080:8080"
   environment:
     KAFKA_CLUSTERS_0_NAME: local
     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_1:9092,kafka_2:9094,kafka_3:9096
     KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

networks:
  kafka-network:
    external: true